# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v2
      with:
        ref: ${{ github.ref }}

    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1
       
    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2
     
    - name: Restore NuGet Packages
      run: nuget restore "Professional Services\Professional Services.sln"
 
    - name: Build and Publish Web App
      run: msbuild "Professional Services\Professional Services.sln" /p:Configuration=Release /p:DeployOnBuild=true /p:WebPublishMethod=Package /p:PackageAsSingleFile=true /p:SkipInvalidConfigurations=true /p:DesktopBuildPackageLocation=".\Publish\WebApp.zip"
 
    - name: Upload Artifact - Web App
      uses: actions/upload-artifact@v1.0.0
      with:
        name: published_webapp
        path: Professional Services/LeaveBot/Publish
    # Copy manifest folder
    - run: xcopy "Professional Services\LeaveBot\Manifest\" "temp"
    - name: Remove File
      uses: JesseTG/rm@v1.0.0
      with:
        # The file path to remove
        path: "temp\Leave App Manifest.zip"
    - name: Compress Teams App
      uses: TonyBogdanov/zip@1.0
      with:
        args: zip -qq -r ./TeamsApp.zip ./temp
    - name: Upload Artifact - Teams App
      uses: actions/upload-artifact@v1.0.0
      with:
        name: teams_app
        path: Professional Services/LeaveBot/Publish
